### PR TITLE
MNT: rerender

### LINKED ISSUE #19: @conda-forge-admin please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #19.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #19

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by zklaus** [comment]
Any reason not to merge this, @hmaarrfk?

**Comment by hmaarrfk** [comment]
I think i was trying to see why this was failing https://github.com/conda-forge/c-blosc2-feedstock/pull/18

I think it is a real issue upstream.

CLosing this.

**Comment by zklaus** [comment]
Huh? But this was working here, no? Ah you mean it has always been working with version <2.1.0 and you wanted to confirm this here to make sure that it is really 2.1.0 that breaks c-blosc2 on aarch64 and ppc64le?

**Comment by zklaus** [comment]
Gotcha. In case you were wondering why I am snooping around: I am trying to get a handle on the outstanding gdal PRs.

**Comment by hmaarrfk** [comment]
Thanks! Is this a blocker for you? We could potentially release the x86 builds before the other architectures. It seems that the M1 builds are also broken.

**Pull request closed without merging**
